resolver: lts-18.13
packages:
  - '.'
  # - haskell-cpython

extra-deps:
  - git: https://github.com/abarbu/haskell-cpython
    commit: 3c3c89acbc5a5fa6d60fc23a148f39eb330ecfac
  # - git: https://github.com/zsedem/haskell-cpython
  #   commit: 42f27b3d9e2c2b5f022ef7e8fd125110c3dadd79

flags: {}
extra-package-dbs: []
nix:
  enable: true
  shell-file: shell.nix
