name: CI
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
        with:
          extra_nix_config: |
            substituters = https://hydra.iohk.io https://cache.nixos.org/ file://$HOME/nix.store
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            require-sigs = false
      - uses: cachix/cachix-action@v10
        with:
          name: gym-haskell
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build dependencies
        run: nix-build shell.nix
      - name: Build package
        run: nix-build -A gym.components.tests
      - name: Build development tools
        run: stack --nix test
